name = "Modpack do Ju"
author = "Vinicius"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2665808edb4df42ab92a60d748de17cb66023ac0371d56a3549afa672f7ea2f"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2"]
