name = "Modpack do Ju"
author = "Vinicius"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ceeb630a7f19aeb9a9c1a5492a0dce6f079cc4b9c1566082db02ddd1ff9ed7d"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2"]
