name = "Modpack do Ju"
author = "Vinicius"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f9181f48375659dcbb98d0962fc6e59bca15ffed3d798e78cfe246abc206a87"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2"]
